<?php

return [
    'G' => [
        'primary_server_name'               => '',
        'primary_database_name'             => '',
        'primary_depot_table'               => '',
        'primary_customer_table'            => '',
        'primary_distributor_table'         => '',
        'primary_product_table'             => '',
        'primary_invoice_master_table'      => '',
        'primary_invoice_details_table'     => '',
        'primary_brand_table'               => '',
        'primary_channeltype_table'         => '',
        'primary_salestype_table'           => '',
        'primary_prodgroup_table'           => '',
        'primary_stock_status_sp'           => '',
        'primary_discount_test_stock_sp'    => '',
        'secondary_server_name'             => '15.235.182.162',
        'secondary_database_name'           => 'tgyphita_laravel',
        'secondary_server_username'         => 'tgyphita_laravel',
        'secondary_database_password'       => '(LQFR=;@@eL{',
        'secondary_depot_table'             => 'beat',
        'secondary_customer_table'          => 'customer',
        'secondary_distributor_table'       => 'dbmastercode',
        'secondary_product_table'           => 'product',
        'secondary_invoice_master_table'    => 'deliveryinvoicemaster',
        'secondary_invoice_details_table'   => 'deliveryinvoicedetails',
        'secondary_brand_table'             => 'prodbrand',
        'secondary_channeltype_table'       => 'channeltype',
        'secondary_salestype_table'         => '',
        'secondary_prodgroup_table'         => 'prodgroup',
        'secondary_stock_status_sp'         => 'usp_StockStatus',
        'secondary_discount_test_stock_sp'  => '',
    ],
    'L' => [
        'primary_server_name'               => '',
        'primary_database_name'             => '',
        'primary_depot_table'               => '',
        'primary_customer_table'            => '',
        'primary_distributor_table'         => '',
        'primary_product_table'             => '',
        'primary_invoice_master_table'      => '',
        'primary_invoice_details_table'     => '',
        'primary_brand_table'               => '',
        'primary_channeltype_table'         => '',
        'primary_salestype_table'           => '',
        'primary_prodgroup_table'           => '',
        'primary_stock_status_sp'           => '',
        'primary_discount_test_stock_sp'    => '',
        'secondary_server_name'             => '15.235.182.162',
        'secondary_database_name'           => 'tgyphita_crm',
        'secondary_server_username'         => 'tgyphita_crm',
        'secondary_database_password'       => 'e[g_F&pG$NO]',
        'secondary_depot_table'             => 'beat',
        'secondary_customer_table'          => 'customer',
        'secondary_distributor_table'       => 'dbmastercode',
        'secondary_product_table'           => 'product',
        'secondary_invoice_master_table'    => 'deliveryinvoicemaster',
        'secondary_invoice_details_table'   => 'deliveryinvoicedetails',
        'secondary_brand_table'             => 'prodbrand',
        'secondary_channeltype_table'       => 'channeltype',
        'secondary_salestype_table'         => '',
        'secondary_prodgroup_table'         => 'prodgroup',
        'secondary_stock_status_sp'         => 'usp_StockStatus',
        'secondary_discount_test_stock_sp'  => '',
    ],
];